/** ****************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ************************************************** */

const express = require('express');
const boom = require('express-boom');
const urlvalidator = require('./api/urlValidation');
const urlShortener = require('./api/urlShortener');

const app = express();
app.use(boom());
const port = process.env.PORT || 3000;

app.get('/api/new/*', (request, response, next) => {
  const inputUrl = decodeURIComponent(request.params[0]);

  // if (!(urlvalidator.isValid(inputUrl))) {
  //   return next();
  // }
  // if (urlvalidator.isDuplicate(inputUrl)) {
  //   return next();
  // }

  urlShortener.insertNew(inputUrl).then((insertedDocument) => {
    console.log(`URL successfully shortened: http://www.example.com/${insertedDocument.shortCode}`); // We return the shortened URL);
  });


  const responseBody = {
    shortUrl: 'https://test.herokuapp.com/8170',
    originalUrl: inputUrl,
  };
  response.json(responseBody);
});
// Error handler for invalid URL
app.use((req, res) => {
  res.boom.badRequest('URL is not valid');
});
// Error handler for duplicate URL a.k.a URL which have already been shortened
app.use((req, res) => {
  res.boom.conflict('URL already shortened');
});

app.listen(port, (err) => {
  if (err) {
    throw err;
  }
});

module.exports = app;
